version: '3.11'

services:
  postgres:
    image: postgres:15-alpine
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rental_bot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"

    # Установка локалей
    command: ["sh", "-c", "apk add --no-cache musl-locales musl-locales-lang && docker-entrypoint.sh postgres"]

volumes:
  01-simple-alchemy-postgres:


