version: '3.11'

services:
  postgres:
    image: postgres:15-alpine
    restart: "no"  # избавляемся от автоматической перезагрузки
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rental_bot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"  # исправлено на правильный путь

volumes:
  01-simple-alchemy-postgres:  # исправлено имя тома


