version: '3.11'

services:
  postgres:
    image: postgres:15-alpine
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rental_bot
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"
    command: [ "sh", "-c", "apk add --no-cache musl-locales musl-locales-lang && docker-entrypoint.sh postgres" ]

  bot:
    build:
      context: .
      dockerfile: Dockerfile # Укажите путь к вашему Dockerfile
    restart: "always"
    depends_on:
      - postgres # Бот будет ждать, пока запустится PostgreSQL
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres/rental_bot # Если необходимо передать URL для БД
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/rental_bot
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "poetry", "run", "alembic", "upgrade", "head" ]
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/rental_bot
    volumes:
      - .:/src

volumes:
  01-simple-alchemy-postgres:


