"""add table citys

Revision ID: 76532b9b8bb7
Revises: 0d18fcdc7920
Create Date: 2024-09-30 22:57:33.347082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76532b9b8bb7'
down_revision: Union[str, None] = '0d18fcdc7920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__citys'))
    )
    op.create_index(op.f('ix__citys_id'), 'citys', ['id'], unique=False)
    op.add_column('apartments', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('apartments_city_id_fkey'), 'apartments', 'citys', ['city_id'], ['id'])
    op.drop_column('apartments', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('apartments_city_id_fkey'), 'apartments', type_='foreignkey')
    op.drop_column('apartments', 'city_id')
    op.drop_index(op.f('ix__citys_id'), table_name='citys')
    op.drop_table('citys')
    # ### end Alembic commands ###
