"""update table booking add column is_completed

Revision ID: 83e2d38b58e0
Revises: be90746a806a
Create Date: 2024-10-04 12:43:45.295013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e2d38b58e0'
down_revision: Union[str, None] = 'be90746a806a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'is_completed')
    # ### end Alembic commands ###
