"""add count_clicks_phone table Landlords

Revision ID: bd1539a65a99
Revises: 7a454bdc600f
Create Date: 2024-10-20 21:03:48.577441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1539a65a99'
down_revision: Union[str, None] = '7a454bdc600f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlords', sa.Column('count_clicks_phone', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlords', 'count_clicks_phone')
    # ### end Alembic commands ###
