"""update table booking

Revision ID: be90746a806a
Revises: 3131e569a55d
Create Date: 2024-10-04 01:39:04.317796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be90746a806a'
down_revision: Union[str, None] = '3131e569a55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('update_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'update_at')
    op.drop_column('bookings', 'create_at')
    # ### end Alembic commands ###
